-- AlterTable
ALTER TABLE "Settings" ADD COLUMN     "beneficiaire" TEXT NOT NULL DEFAULT 'PATRO ST NICOLAS GARCONS ENGHIEN',
ADD COLUMN     "bic" TEXT NOT NULL DEFAULT 'GKCCBEBB',
ADD COLUMN     "iban" TEXT NOT NULL DEFAULT 'BE56 7755 9576 1388';
